# Generated by Django 5.2.1 on 2025-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model was created')),
                ('first_name', models.CharField(help_text='First name of the person', max_length=30)),
                ('last_name', models.CharField(help_text='Last name of the person', max_length=30)),
                ('phone', models.CharField(help_text='Phone number of the person', max_length=15)),
                ('email', models.EmailField(help_text='Email address of the person', max_length=50)),
            ],
        ),
    ]
