# Generated by Django 5.2.1 on 2025-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(max_length=2),
        ),
    ]
