# Generated by Django 5.2.1 on 2025-06-09 05:00

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_cliente_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Male'), ('femenino', 'Female'), ('otro', 'Other'), ('prefiero_no_decir', 'Rather not say')], default='prefiero_no_decir', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=django_countries.fields.CountryField(default='MX', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_lealtad',
            field=models.CharField(choices=[('bronze', '🥉 Bronze'), ('silver', '🥈 Silver'), ('gold', '🥇 Gold'), ('platinum', '💎 Platinum')], default='bronze', max_length=20),
        ),
    ]
