# Generated by Django 5.2.1 on 2025-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_cliente_genero_alter_cliente_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_aniversario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Female'), ('masculino', 'Male'), ('otro', 'Other')], default='femenino', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_lealtad',
            field=models.CharField(blank=True, choices=[('bronze', '🥉 Bronze'), ('silver', '🥈 Silver'), ('gold', '🥇 Gold'), ('platinum', '💎 Platinum')], default='bronze', max_length=20, null=True),
        ),
    ]
