# Generated by Django 5.2.1 on 2025-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_cliente_fecha_aniversario_alter_cliente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('masculino', '👨 Masculino'), ('femenino', '👩 Femenino'), ('otro', '⚧️ Otro')], default='femenino', max_length=20),
        ),
    ]
