# Generated by Django 5.2.1 on 2025-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_cliente_apellido_materno_alter_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='area_code',
            field=models.CharField(default='+52', help_text='Area code with country code', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(help_text='Phone number wihout area code', max_length=15),
        ),
    ]
