# Generated by Django 5.2.1 on 2025-06-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_cliente_area_code_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', '👨 Male'), ('F', '👩 Female'), ('Other', '⚧️ Other')], default='femenino', max_length=20),
        ),
    ]
