# Generated by Django 5.2.1 on 2025-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_cliente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('👨 Male', '👨 Male'), ('👩 Female', '👩 Female'), ('⚧️ Other', '⚧️ Other')], default='👩 Female', max_length=20),
        ),
    ]
