# Generated by Django 5.2.1 on 2025-06-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_cliente_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
