# Generated by Django 5.2.1 on 2025-06-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_hotel_alias_alter_hotel_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='specialization',
        ),
    ]
