# Generated by Django 5.2.1 on 2025-06-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_activity_capacity_and_more'),
    ]

    operations = [
    ]

