# Generated by Django 5.2.1 on 2025-06-19 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_hotel_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tipo_viaje', models.CharField(choices=[('honeymoon', '💕 Luna de Miel'), ('anniversary', '🎉 Aniversario'), ('birthday', '🎂 Cumpleaños'), ('vacation', '🏖️ Vacaciones'), ('business', '💼 Viaje de Negocios'), ('family', '👨\u200d👩\u200d👧\u200d👦 Viaje Familiar'), ('graduation', '🎓 Graduación'), ('wedding', '💒 Boda'), ('other', '✨ Otro')], default='vacation', max_length=50, verbose_name='Celebración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='website.cliente')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
                'ordering': ['-created_at'],
            },
        ),
    ]
