# Generated by Django 5.2.1 on 2025-06-19 01:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Presupuesto total en MXN', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='folio',
            name='comments',
            field=models.TextField(blank=True, help_text='Comentarios sobre el folio', null=True),
        ),
    ]
